### ISSUE TITLE
how to patch minecraft HOSE project for mac / linux

### ISSUE THREAD

**Issue by ausir0726** [softpak/HOSE#13]
patch flow for mac / linux ( need modify for window )
-- you should install wget and git first
1. download Spigot BuildTool / run BuildTool.jar

``` bash
wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar ;
java -jar BuildTools.jar ;
```

  -- it should get spigot-1.9.2.jar 
1. make maven runnable

``` bash
sudo chmod 777 apache-maven-3.2.5/bin/mvn ;
```
1. download HOSE project
   -- it's will download master version .

``` bash
cd Spigot/Spigot-Server/;
git clone https://github.com/softpak/HOSE.git ;
```
1. copy pom.xml and patch

``` bash
cp HOSE/pom.xml . ;
cd src ; patch -p1 < ../HOSE/src.patch ;
```
1. build HOSE spigot

``` bash
cd .. ; ../../apache-maven-3.2.5/bin/mvn clean install ;
```
1. find spigot-1.9.2-R0.1-SNAPSHOT.jar in target folder and rename hose-1.9.2.jar
   -- you need find correct spigot version jar file . 1.9.2 just for example .

``` bash
cd target ; mv spigot-1.9.2-R0.1-SNAPSHOT.jar hose-1.9.2.jar ;
```
1. run hose-1.9.2.jar with -noverify

``` bash
java -jar -noverify hose-1.9.2.jar ;
```

**Comment by leang97** [comment]
can you give a latest intruction on how to build it on latest buildtools on spigot? I keep getting rebuild errors.

**Comment by loveyanbei** [comment]
Kept getting this
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[151] The method getServer() is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[193] methodProfiler cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[199] methodProfiler cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[236] isClientSide cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[253] isClientSide cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[493] methodProfiler cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[494] isClientSide cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[507] methodProfiler cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[633] methodProfiler cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[635] methodProfiler cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[642] methodProfiler cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[644] methodProfiler cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[645] methodProfiler cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[649] methodProfiler cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[650] methodProfiler cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[654] The method getServer() is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[656] methodProfiler cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[657] methodProfiler cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[661] methodProfiler cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[662] methodProfiler cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[664] methodProfiler cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[672] methodProfiler cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[673] methodProfiler cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[675] methodProfiler cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[677] methodProfiler cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[679] methodProfiler cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[680] methodProfiler cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[1049] The method getServer() is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[1054] The method getServer() is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[1064] isClientSide cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[1070] isClientSide cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[1092] isClientSide cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[1137] The method getServer() is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityInsentient.java:[1283] The method getServer() is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityWitherSkull.java:[39] isClientSide cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityWitherSkull.java:[75] The method getServer() is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockJukeBox.java:[19] The method setTypeAndData(BlockPosition, IBlockData, int) is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockJukeBox.java:[27] isClientSide cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockJukeBox.java:[32] The method setTypeAndData(BlockPosition, IBlockData, int) is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockJukeBox.java:[38] isClientSide cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockJukeBox.java:[50] random cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockJukeBox.java:[51] random cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockJukeBox.java:[52] random cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockJukeBox.java:[69] isClientSide cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockChorusFlower.java:[78] The method getWorld() is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockChorusFlower.java:[79] The method getWorld() is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockChorusFlower.java:[83] The method setTypeAndData(BlockPosition, IBlockData, int) is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockChorusFlower.java:[104] The method getWorld() is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockChorusFlower.java:[105] The method getWorld() is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockChorusFlower.java:[117] The method setTypeAndData(BlockPosition, IBlockData, int) is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockChorusFlower.java:[155] The method setTypeAndData(BlockPosition, IBlockData, int) is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockChorusFlower.java:[160] The method setTypeAndData(BlockPosition, IBlockData, int) is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockChorusFlower.java:[253] The method setTypeAndData(BlockPosition, IBlockData, int) is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockChorusFlower.java:[271] The method setTypeAndData(BlockPosition, IBlockData, int) is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockChorusFlower.java:[289] The method setTypeAndData(BlockPosition, IBlockData, int) is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockChorusFlower.java:[296] The method setTypeAndData(BlockPosition, IBlockData, int) is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockSapling.java:[35] isClientSide cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockSapling.java:[37] spigotConfig cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockSapling.java:[39] captureTreeGeneration cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockSapling.java:[43] captureTreeGeneration cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockSapling.java:[44] capturedBlockStates cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockSapling.java:[47] The method getWorld() is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockSapling.java:[48] capturedBlockStates cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockSapling.java:[49] capturedBlockStates cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockSapling.java:[69] The method setTypeAndData(BlockPosition, IBlockData, int) is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockSapling.java:[171] The method setTypeAndData(BlockPosition, IBlockData, int) is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockSapling.java:[172] The method setTypeAndData(BlockPosition, IBlockData, int) is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockSapling.java:[173] The method setTypeAndData(BlockPosition, IBlockData, int) is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockSapling.java:[174] The method setTypeAndData(BlockPosition, IBlockData, int) is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockSapling.java:[176] The method setTypeAndData(BlockPosition, IBlockData, int) is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockSapling.java:[181] The method setTypeAndData(BlockPosition, IBlockData, int) is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockSapling.java:[182] The method setTypeAndData(BlockPosition, IBlockData, int) is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockSapling.java:[183] The method setTypeAndData(BlockPosition, IBlockData, int) is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockSapling.java:[184] The method setTypeAndData(BlockPosition, IBlockData, int) is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockSapling.java:[186] The method setTypeAndData(BlockPosition, IBlockData, int) is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockSapling.java:[211] random cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityTracker.java:[115] players cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityTracker.java:[178] players cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityTracker.java:[210] players cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockCrops.java:[58] spigotConfig cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockCrops.java:[84] random cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockCrops.java:[145] isClientSide cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/BlockCrops.java:[152] random cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityOcelot.java:[124] isClientSide cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityOcelot.java:[132] isClientSide cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityOcelot.java:[136] random cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityOcelot.java:[192] random cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityOcelot.java:[237] random cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityTrackerEntry.java:[243] The method getServer() is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/MinecraftServer.java:[328] The method getWorld() is undefined for the type WorldServer
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/MinecraftServer.java:[359] The method getWorld() is undefined for the type WorldServer
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/MinecraftServer.java:[390] The method getWorld() is undefined for the type WorldServer
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/MinecraftServer.java:[442] worldProvider cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/MinecraftServer.java:[702] The method getWorld() is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/MinecraftServer.java:[793] timings cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/MinecraftServer.java:[795] timings cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/MinecraftServer.java:[809] timings cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/MinecraftServer.java:[811] timings cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/MinecraftServer.java:[826] timings cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/MinecraftServer.java:[828] timings cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/MinecraftServer.java:[1256] worldProvider cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityItemFrame.java:[36] isClientSide cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityItemFrame.java:[189] isClientSide cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityItemFrame.java:[195] isClientSide cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntitySmallFireball.java:[23] isClientSide cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntitySmallFireball.java:[33] The method getServer() is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityMinecartAbstract.java:[113] The method getServer() is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityMinecartAbstract.java:[121] isClientSide cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityMinecartAbstract.java:[130] The method getServer() is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityMinecartAbstract.java:[147] The method getServer() is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityMinecartAbstract.java:[218] isClientSide cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityMinecartAbstract.java:[219] methodProfiler cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityMinecartAbstract.java:[220] The method getMinecraftServer() is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityMinecartAbstract.java:[230] worldProvider cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityMinecartAbstract.java:[255] methodProfiler cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityMinecartAbstract.java:[258] isClientSide cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityMinecartAbstract.java:[323] The method getWorld() is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityMinecartAbstract.java:[328] The method getServer() is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityMinecartAbstract.java:[331] The method getServer() is undefined for the type World
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityMinecartAbstract.java:[672] isClientSide cannot be resolved or is not a field
[ERROR] /home/autossh/build/Spigot/Spigot-Server/src/main/java/net/minecraft/server/EntityMinecartAbstract.java:[680] The method getServer() is undefined for the type World
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
autossh@iZ94kjgm9l6Z:~/build/Spigot/Spigot-Server$

**Comment by softpak** [comment]
Try to use my pom.xml file.
It needs jdk and other libs to support jdk1.7.

**Comment by loveyanbei** [comment]
Replaced but no use.
Output of uname -a

Linux iZ94kjgm9l6Z 3.13.0-86-generic #130-Ubuntu SMP Mon Apr 18 18:27:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

javac  -version 

javac 1.8.0_91

**Comment by loveyanbei** [comment]
I downloaded latest release with my vps but I'm still hoping to build on my own 
Thx
