### ISSUE TITLE
游戏内无法自然生成怪物

### ISSUE THREAD

**Issue by ccxufo** [softpak/HOSE#18]
如题， 
僵尸，骷髅，猪人，末影人，JJ怪等都无法自然出现，即使晚上也不行（怪物蛋可以），如果我使用spigot是没问题的，但是hose运行下世界无法自然生成怪物，hose版本为1.8.8_0317

**Comment by softpak** [comment]
可能是設定檔的問題，
先前有遇到國外玩家發生地圖無法生成的情況，
修改設定後就好了。

你先用預設設定檢查看看正不正常。

**Comment by ccxufo** [comment]
嘛，是这样。我先用spigot跑一遍获存档，再将伺服器核心换成hose。也就是说我从spigot换到hose时出现的实体无法产生的现象

**Comment by ccxufo** [comment]
嘛，首先对我提交的bug感到抱歉，我自己也找到了原因所在，我自己用的是的jre7，换成jre8后就好了，之前一直用paperspigot,我以为hose也能用jre7呢~
