### ISSUE TITLE
请问这是付费软件？

### ISSUE THREAD

**Issue by ccxufo** [softpak/HOSE#2]
Trial has expired.

**Comment by softpak** [comment]
不是，只是我怕有BUG所以給了一個期限，目前是發現List存有BUG，所以目前正在重新設計。

**Comment by ccxufo** [comment]
我想问一下，作者目前使用的CPU型号是？不同型号的CPU对TPS的影响较大，我想对比一下我这边的情况

**Comment by softpak** [comment]
開發測試的CPU是I5-3470
