### ISSUE TITLE
Help with patching

### ISSUE THREAD

**Issue by ajthemacboy** [softpak/HOSE#3]
I'm not a developer and the instructions in the README are beyond me. Can basic instructions on how to patch, such as the following, be provided for noobs?

1. How do I import the project into Eclipse? 
2. Do I run the patch command in the `Spigot-Server` src directory, or the `Bukkit`\`CraftBukkit` source directory?
3. How do I build in Eclipse, and why can't I just use `gradlew build`? Do I *need* Eclipse for this process or can it be done without Eclipse?

Thanks, and sorry for the ignorant questions.

**Comment by softpak** [comment]
This project is still under development. It has memory leaks when using async threads. JVM's GC can not recycle PathPoint objects and causing lags. When I solve this issue. I will make a noob tool for it. Just like Spigot. So before that, you still need an IDE tool to build it.

**Comment by softpak** [comment]
You need to path src folder in spigot-server. Not the bukkit. It is a marven project. Gradle is not working.

**Comment by ajthemacboy** [comment]
Sounds good, and great work. I'll be waiting :)

**Comment by softpak** [comment]
You can download the release now. I solved all the issues.

**Comment by ajthemacboy** [comment]
Closed
