### ISSUE TITLE
Is the project still active?

### ISSUE THREAD

**Issue by ThijnBeers** [softpak/HOSE#31]
Hello,

I was wondering if the project is still active.

**Comment by ataranlen** [comment]
I would say yes. The last commit was only a month ago on master: https://github.com/softpak/HOSE/commits/master

**Comment by ThijnBeers** [comment]
Before that, every few days there was an update.
Ofcourse he can take all the time he likes but I was just wondering.

**Comment by softpak** [comment]
Will, I am a little busy right now.
I am trying to modify the chunk provider server.
It`s the bottle neck right now.
So please wait for a few weeks.

**Comment by ThijnBeers** [comment]
Thanks for the update and success with it :D
