### ISSUE TITLE
Issue starting server

### ISSUE THREAD

**Issue by BlueSoapTurtle** [softpak/HOSE#39]
I downloaded the latest hose-1.11.2.jar, put it in a folder and made a .bat file to run it

`@echo off

java -Xms4096M -Xmx4096M -jar hose-1.11.2.jar
pause`

and when I start it, this happens(Log): 
https://hastebin.com/iriyipahik.log

**Comment by softpak** [comment]
add -noverify

**Comment by BlueSoapTurtle** [comment]
Thanks!
