### ISSUE TITLE
An error has been occurred when starting

### ISSUE THREAD

**Issue by Mon-chi** [softpak/HOSE#40]
Using latest spigot for now (CraftBukkit commit 775f1e1f7f5)

`Loading libraries, please wait...
[STDERR]: java.lang.VerifyError: Inconsistent stackmap frames at branch target 52
Exception Details:
  Location:
    net/minecraft/server/v1_11_R1/DataWatcher.b(Lnet/minecraft/server/v1_11_R1/PacketDataSerializer;)Ljava/util/List; @52: aload_1
  Reason:
    Type top (current frame, locals[4]) is not assignable to integer (stack map, locals[4])
  Current Frame:
    bci: @24
    flags: { }
    locals: { 'net/minecraft/server/v1_11_R1/PacketDataSerializer', 'java/util/ArrayList', integer, 'net/minecraft/server/v1_11_R1/DataWatcherSerializer' }
    stack: { 'net/minecraft/server/v1_11_R1/DataWatcherSerializer' }
  Stackmap Frame:
    bci: @52
    flags: { }
    locals: { 'net/minecraft/server/v1_11_R1/PacketDataSerializer', 'java/util/ArrayList', integer, 'net/minecraft/server/v1_11_R1/DataWatcherSerializer', integer }
    stack: { }
  Bytecode:
    0x0000000: 014c a700 4d2b c700 07b8 0154 4c2a b601
    0x0000010: 703d 1cb8 0173 4e2d c700 1cbb 0175 59bb
    0x0000020: 0081 5913 0165 b700 861c b600 8ab6 0094
    0x0000030: b701 76bf 2bbb 0007 592d 1504 b900 a002
    0x0000040: 002d 2ab9 0179 0200 b700 ceb6 0157 572a
    0x0000050: b601 7d59 3604 1100 ffa0 ffac 2bb0
  Stackmap Table:
    append_frame(@5,Object[#327],Integer)
    same_frame(@13)
    append_frame(@52,Object[#125],Integer)
    chop_frame(@79,3)
[STDERR]:       at net.minecraft.server.v1_11_R1.Entity.<clinit>(Entity.java:117)
[STDERR]:       at net.minecraft.server.v1_11_R1.RecipeShulkerBox.a(RecipeShulkerBox.java:8)
[STDERR]:       at net.minecraft.server.v1_11_R1.CraftingManager.<init>(CraftingManager.java:44)
[STDERR]:       at net.minecraft.server.v1_11_R1.CraftingManager.<clinit>(CraftingManager.java:16)
[STDERR]:       at net.minecraft.server.v1_11_R1.StatisticList.b(SourceFile:140)
[STDERR]:       at net.minecraft.server.v1_11_R1.StatisticList.a(SourceFile:131)
[STDERR]:       at net.minecraft.server.v1_11_R1.DispenserRegistry.c(DispenserRegistry.java:659)
[STDERR]:       at net.minecraft.server.v1_11_R1.MinecraftServer.main(MinecraftServer.java:860)
[STDERR]:       at org.bukkit.craftbukkit.Main.main(Main.java:210)`

**Comment by softpak** [comment]
Add -noverify in the shell script.
You can take a look at HOSE.sh.
