### ISSUE TITLE
Newer Minecraft versions

### ISSUE THREAD

**Issue by AuxiliumCDNG** [softpak/HOSE#57]
Hi! Is there a possibility to get this running with the newer Minecraft versions; eg. 1.15.2? I really miss the console autofill thing and other features of the new versions.
I've seen that this repo wasn't upgrade in 6 years but I was hoping to get at least some kind of workaround.
Thanks!

**Comment by softpak** [comment]
It`s harder and harder to have the entity tick multithreaded. I am going to try another way. I am working on a bungeecord plugin to separate 3 dimensions into 3 different servers.

**Comment by AuxiliumCDNG** [comment]
Thanks a lot for your great work. It's sad that it's not possible anymore in the new versions. But keep the great work up. And thanks for the fast reply btw.
