### ISSUE TITLE
关于大量使用CopyOnWriteArrayList可能带来的性能问题

### ISSUE THREAD

**Issue by andylizi** [softpak/HOSE#6]
虽然我不能肯定您是哪国人, 但看得懂中文就用中文吧
粗略了看了下原理, 发现其中大量的List等集合都被换成了CopyOnWriteArrayList, 但是据我所知CopyOnWriteArrayList的原理是, 写入时把原数组复制一份. 所以只适用于读多写少的场合. 大量的写操作会消耗很多内存. 虽然我对并发的了解不多, 但还是觉得很奇怪, 想来问一问. 
望解答:-)

**Comment by jiongjionger** [comment]
正因为写入时做了快照拷贝，写入完后直接让指针指向新的数组对象，保证了线程安全。用于保存实体和区块的数组大小并不大，额外内存占用问题应该不显著。说实话，由于所有代码都在一个patch里面，我也只是粗略的看了一遍。个人觉得一些写为主的还是使用Collections.synchronizedList来做锁同步更好一点。

**Comment by zhouhaha** [comment]
虽然大小不大, 但是大量的写入, 每次都复制一份的消耗还是很可怕的. JVM的垃圾回收本来就..

**Comment by softpak** [comment]
記憶體使用方面可以用jmap來監視，就我檢查過是沒問題的，gc正常運作。會用copyinwrite主要是因為出現concurrent exception，加上本身多數的型別都是list，為了減少修改的部分就只能先這樣，否則我都會改成queue。

**Comment by zhouhaha** [comment]
是否有可能使用[Amino并发框架](http://amino-cbbs.sourceforge.net/)([github](https://github.com/figoxu/aminocbbs))

**Comment by softpak** [comment]
Lockfreelist看起來是個好用的東西，感謝提供lib，我會試試看的。

**Comment by zhouhaha** [comment]
我昨天测试了一下LockFreeList和LockFreeVector（说明中，LockFreeList基于链表，相当于LinkedList，LockFreeVector基于原子数组，相当于ArrayList），速度和占用内存还是有点大了..我正在试着自己用原子数组实现ConcurrentList

**Comment by jiongjionger** [comment]
无锁实现在竞争激烈的时候开销非常非常大，这个最好做对比测试再决定用哪种。

**Comment by softpak** [comment]
其實我比較偏向用google或java本身的lib，畢竟相比之下更為嚴謹且集大成。

**Comment by zhouhaha** [comment]
前提是如果有. 我找了半天也就找到一个Amino了，并且在百度上的介绍也不多
很奇怪,apache-commons和guava几乎什么功能都集成了，但在并发方面一个也没有
难道真的这么难?

**Comment by softpak** [comment]
併發的部分Java本身就很多了，
我列個常見的對照表：

     1. CopyOnWriteArrayList   (Thread safe arrayList)

     2. ConcurrentLinkedDeque  (Thread safe LinkedList)

     3. ConcurrentHashMap      (Thread safe HashMap)

     4. CopyOnWriteArraySet    (Thread safe HashSet)

     5. ConcurrentSkipListMap  (Thread Safe TreeMap)

     6. ConcurrentSkipListSet  (Thread Safe TreeSet)

     7. ConcurrentLinkedQueue  (Thread safe Priority Queue)

這些也是我優先使用的。

**Comment by loveyanbei** [comment]
http://stackoverflow.com/questions/3917810/copyonwritearray-or-vector
突然发现你也是半个中国人23333
好吧，这篇回答提到，用哪个东西做list，要看读写频率，经常写的list建议拿vector代替

**Comment by softpak** [comment]
主要是因為MC都用list，而list的大小約在1萬以下，如果使用Vector還要在執行完轉成List，否則插件跟指令會無法運作，因為怕轉換過程被插入或什麼的會導致資料不全，所以list的部分並沒有打算再修改。說個題外話，之前試著將entityslice改成vector，要改到了大約30多個檔案的宣告，而程式變得反而容易出錯，追蹤之下，最後變成要去修改官方的server.jar，光這點侵權就不適合了。但mojang確實逐步進步中，是可以期待這部分的改善的。
