### ISSUE TITLE
關於patch您的專案後無法編譯伺服器的jar檔

### ISSUE THREAD

**Issue by yuk7778** [softpak/HOSE#7]
編譯紀錄:
cd C:\Users\USER\Desktop\BuildTools\Spigot\Spigot-Server; "JAVA_HOME=C:\\Program Files\\Java\\jdk1.8.0_73" cmd /c "\"\"C:\\Program Files\\NetBeans 8.1\\java\\maven\\bin\\mvn.bat\" -Dmaven.ext.class.path=\"C:\\Program Files\\NetBeans 8.1\\java\\maven-nblib\\netbeans-eventspy.jar\" -Dfile.encoding=UTF-8 install\""
Scanning for projects...
                                                                        
------------------------------------------------------------------------
Building Spigot 1.8.8-R0.1-SNAPSHOT
------------------------------------------------------------------------

--- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ spigot ---

--- scriptus:0.2:describe (ex-spigot) @ spigot ---
Set property "spigot.desc" to "git-Spigot-e4d4710"

--- scriptus:0.2:describe (ex-craftbukkit) @ spigot ---
Set property "craftbukkit.desc" to "-e1ebe52"

--- maven-resources-plugin:2.6:resources (default-resources) @ spigot ---
Using 'UTF-8' encoding to copy filtered resources.
Copying 4 resources

--- maven-compiler-plugin:3.1:compile (default-compile) @ spigot ---
Changes detected - recompiling the module!
-------------------------------------------------------------
COMPILATION ERROR : 
-------------------------------------------------------------
C:\Users\USER\Desktop\BuildTools\Spigot\Spigot-Server\src\main\java\net\minecraft\server\ItemStack.java:[137] The constructor StructureGrowEvent(Location, TreeType, boolean, Player, Queue<BlockState>) is undefined
C:\Users\USER\Desktop\BuildTools\Spigot\Spigot-Server\src\main\java\org\bukkit\craftbukkit\chunkio\ChunkIOProvider.java:[58] The method setAsynchronous() is undefined for the type Event
C:\Users\USER\Desktop\BuildTools\Spigot\Spigot-Server\src\main\java\net\minecraft\server\BlockSapling.java:[54] The constructor StructureGrowEvent(Location, TreeType, boolean, null, Queue<BlockState>) is undefined
C:\Users\USER\Desktop\BuildTools\Spigot\Spigot-Server\src\main\java\org\bukkit\craftbukkit\event\CraftEventFactory.java:[127] The constructor BlockMultiPlaceEvent(Queue<BlockState>, BlockState, Block, Block, ItemStack, Player, boolean) is undefined
4 errors 
---------------

**Comment by softpak** [comment]
請把API也一併PATCH之後再一起編譯。
Date: Thu, 24 Mar 2016 07:07:16 -0700

**Comment by yuk7778** [comment]
編譯成功了 感謝大大的解答!
