### ISSUE TITLE
是否有在稍微詳盡一點的說明

### ISSUE THREAD

**Issue by ausir0726** [softpak/HOSE#8]
對 java 不是太熟

所以 import  Spigot/Spigot-Server 一直有問題
也無法再編譯成功

不知道是不是有在稍微清楚一點的 import 與 編譯作法
google 了但因為關鍵字一直會被開發新插件 import spigot 洗掉...

thanks.

**Comment by ausir0726** [comment]
嗯～

好像有弄出來了

1. build spigot
[ java -jar BuildTools.jar ]

2. setting mvn 
[ /path to apache-maven-3.2.5/bin/mvn -version ] 
要把 mvn 給予執行權限 然後把 java home 設定好

3. download patch and goto Spigot/Spigot-Server/src upate patch
[ patch -p1 < ../src.patch ]

4. build spigot.jar
[ /path to apache-maven-3.2.5/bin/mvn clean install ]

不知道是否正確

希望早日有 1.9 的版本可以測試～
謝謝

**Comment by softpak** [comment]
應該是有辦法簡化成單純將patch檔放到patch資料夾，直接執行buildtools的辦法。另外1.9已經開始在開發了，使用了jdk1.7的新語法，能解決jdk1.6的諸多問題，之後會順便把1.8.8的bug用相同方式修正。

**Comment by ausir0726** [comment]
瞭解

因為看更新，以為是已經支援 1.9 了...

謝謝

**Comment by ausir0726** [comment]
剛剛用 1.8.8 測試可以 patch 了
但是我再 mvn clean install 的時候還是 BUILD FAILURE

不過沒關系
因為我們現在也已經用 1.9.2 了 >"< 玩家回不去了

所以只好乖乖支持 1.9 .... 

是我自己誤會以為支援 1.9 了
希望 1.9 可以直接加進去  BuildTools ，不然編譯要下載回來有點麻煩 XD

抱歉，可以幫我 CLOSE 了！

謝謝
